web:
  extends:
    file: config.yml
    service: web
  expose:
    - "8000"
  volumes:
    - /tmp
    - ./web:/usr/src/app
  command: /usr/local/bin/gunicorn sharemusic.wsgi:application -w 6 -b :8000 --timeout 5000

nginx:
  extends:
    file: config.yml
    service: nginx
  image: nginx:latest
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf

postgres:
  image: postgres:9.5
  expose:
    - "5432"

redis:
  image: redis:latest
  expose:
    - "6379"

data:
  image: postgres:9.5
  volumes:
    - /var/lib/postgresql
  command: "true"
